services:
  app_lcc:
    build: backend
    mem_limit: 1g   # Limita la memoria RAM a 1GB
    cpus: 1         # Limita el uso a 1 CPU
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://lcc:5432/db_lcc
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      lcc:
        condition: service_healthy

  lcc:
    image: postgres:15
    mem_limit: 1g   # Limita la memoria RAM a 1GB
    cpus: 1         # Limita el uso a 1 CPU
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_lcc
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data  # ⬅️ Volumen persistente
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_lcc"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: frontend
    mem_limit: 1g   # Limita la memoria RAM a 1GB
    cpus: 1         # Limita el uso a 1 CPU
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app_lcc

volumes:
  pgdata:  # ⬅️ Define el volumen para PostgreSQL
